# alertmanager.yml
route:
  receiver: "default"
  group_by: ["alertname", "camera", "incident_id"]

  # ↓↓↓ Make notifications immediate
  group_wait: 0s          # don’t wait to form a group
  group_interval: 1s      # send subsequent updates nearly immediately
  repeat_interval: 4h

  routes:
    - matchers:
        - alertname="agguard_incident_open"
      receiver: "agguard-receivers"

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://alerts-gateway:8090/am/webhook"

  - name: "agguard-receivers"
    webhook_configs:
      - url: "http://alerts-gateway:8090/am/webhook"
        send_resolved: true        # ← keep this ON

    # slack_configs:
    #   - api_url: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
    #     channel: "#security-alerts"
    #     send_resolved: true
    #     text: >
    #       *{{ .CommonLabels.camera }}* {{ .CommonLabels.anomaly }} ({{ .Status }})
    #       HLS: {{ (index .CommonAnnotations "hls") }}
    #       VOD: {{ (index .CommonAnnotations "vod") }}
    # email_configs:
    #   - to: "yehudit50402@gmail.com"
    #     from: "yehudit50402@gmail.com"
    #     smarthost: "mailrelay:25"
    #     require_tls: false
    #     send_resolved: true
